services:
    redis:
        image: redis
        ports:
            - '6379:6379'
    mysql:
        image: mysql:8.0
        container_name: orders
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: orders
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./tmp/docker/mysql:/var/lib/mysql
            - ./concurrency-control/init.sql:/docker-entrypoint-initdb.d/init.sql
