services:
    redis:
        image: redis
        ports:
            - '6379:6379'
    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: orders
            MYSQL_USER: user
            MYSQL_PASSWORD: password
